Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.box_url = "file:///Users/chendong/Downloads/vagrant-boxes/xenial-server-cloudimg-amd64-vagrant.box"

  config.vm.provision "shell", path: "bootstrap.sh"

  # Ranges: 192.168.56.0/21
  # 192.168.56~63.0~255
  config.vm.network "private_network", ip: "192.168.56.4"
end